### ISSUE TITLE
Getting Involved Information link in readme is not working 

### ISSUE THREAD

**Issue by anjansrivathsav** [coala/coala-html#137] opened 2017-11-10 17:48 UTC
The link getting involved information link is redirecting to a page that does not exist

**Comment by prnvdixit** [comment] 2017-11-10 18:19
Duplicate of https://github.com/coala/coala-html/issues/128 - Please close this issue. 😄
Thanks for reporting anyway 👍.

**Comment by anjansrivathsav** [comment] 2017-11-10 18:23
Ok

On 10 Nov 2017 23:49, "Pranav Dixit" <notifications@github.com> wrote:

Duplicate of #128 <https://github.com/coala/coala-html/issues/128> - Please
close this issue. 😄
Thanks for reporting anyway 👍.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/coala/coala-html/issues/137#issuecomment-343547869>,
or mute
the thread

**Comment by prnvdixit** [comment] 2017-11-10 18:32
BTW if you are looking to get started with project - Head to https://coala.io/chat and just say "Hello World". You would get guided from there 👍....

**Closed** 2017-11-10 18:34 UTC
